### ISSUE TITLE
Типы ячеек

### ISSUE THREAD

**Issue by el-strannik** [Avemey/zexmlss#16]
При создании новой ячейки TZCell через Create тип по умолчанию ставится ZEString, а при чтении файла с диска (созданного из Excel) тип по умолчанию (для всех ячеек, для которых тип не указан явно) ставится ZENumber. Это чем-то обусловлено?

Мне кажется правильнее будет при чтении тоже ставить ZEString или, как вариант, добавить настройку с дефолтным типом и при чтении ориентироваться на него.

Могу поправить сам, но хотелось бы знать Ваше мнение.

**Comment by el-strannik** [comment]
Или добавить новый тип (например, ZEDefault или ZEGeneral), который будет читаться из "неуказанного" типа и при записи также явно не указываться.

`<c r="A1" s="1">`

вместо

`<c r="A1" s="1" t="n">`

**Comment by Avemey** [comment]
Насколько помню, мне в основном приходилось экспортировать строки, а читать number, поэтому так и реализовано. Над этим можно подумать. Сейчас при создании документа можно воспользоваться свойствами AsDouble/AsInteger/AsDateTime в TZCell (Cell[0, 0].AsInteger := 10;)  для установки нужного типа, поэтому создание доукмента не нуждается в доработке, имхо. А вот открытие с неизвестным типом в xlsx можно и доработать.

**Comment by Avemey** [comment]
Но перед реализацией нужно внимательно прочитать, что по этому поводу указано в документации на xlsx: http://www.ecma-international.org/publications/standards/Ecma-376.htm
(литература не для слабонервных)

**Comment by Avemey** [comment]
Если глянуть на странице 1588 (4-ое издание) параграф 18.3.1.4 c (Cell), то там вроде как ничего не указано про то, что атрибут t может отсутствовать. Наверное, из тех файлов, которые у меня были, был сделан вывод, что в данном случае нужно брать number.

**Comment by el-strannik** [comment]
> там вроде как ничего не указано про то, что атрибут t может отсутствовать

Но не сказано и обратного, что этот атрибут должен быть обязательным. Более того, в [этом примере](https://www.dropbox.com/s/4gsawuoars18kwi/celltype.png?dl=0) нет t. Excel 2013 и LO Calc, если на листе **в пустой** ячейке указать стиль, при сохранении запишут эту ячейку без t. Предлагаю всё таки добавить тип ZEGeneral, для чтения и записи без указания типа

> AsDouble/AsInteger/AsDateTime

Тогда нужно еще свойство AsString. Например, есть шаблон, созданный непосредственно в Excel. При чтении у ячеек с отсутствующим типом ставится тип ZENumber. Через `.Data := 'ololol'` значение выставляется, но тип не меняется! Если такой файл сохранить и попытаться открыть в Excel - будет ошибка.

**Comment by el-strannik** [comment]
#20
